sudo: false

language: python

python:
  - "3.4"

env:
  - PIP_DOWNLOAD_CACHE="pipcache"

cache:
  directories:
    - pipcache

install:
  - pip install -r requirements.txt

script:
  - make html

branches:
  only:
    - master

after_success:
  - mkdir -p ~/.ssh/
  - echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
  - chmod go-rwx ~/.ssh/
  - make publish

addons:
  ssh_known_hosts:
  - ash-alpha.ironfroggy.com
